In [4]:
import numpy as np

def conv2d(in_tensor, weight, bias=None, stride=1, padding=0, dilation=1):
    batch_size, in_channels, in_height, in_width = in_tensor.shape
    out_channels, _, weight_height, weight_width = weight.shape

    padded_input = np.pad(in_tensor, padding, mode = 'constant')
    out_height = int((in_height + 2 * padding - dilation * (weight_height - 1) - 1) / stride) + 1
    out_width = int((in_width + 2 * padding - dilation * (weight_width - 1) - 1) / stride) + 1
  
    out_tensor = np.zeros((batch_size, out_channels, out_height, out_width))
  
    for b in range(batch_size):
        for o in range(out_channels):
            for i in range(in_channels):
                for h in range(0, in_height - weight_height + 1, stride):
                    for w in range(0, in_width - weight_width + 1, stride):
                        out_tensor[b, o, h // stride, w // stride] += np.sum(
                            padded_input[b, i, h:h + weight_height, w:w + weight_width] * weight[o,i])
                  
    if bias is not None:
        out_tensor += bias.reshape[1, -1, 1, 1]
  
    return out_tensor

In [5]:
import torch

input_tensor = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]]])
filters = np.array([[[[1, 1], [1, 1]]]])

torch_conv = torch.nn.functional.conv2d(torch.Tensor(input_tensor), torch.Tensor(filters))
my_conv = conv2d(input_tensor, filters)
print("Результат работы исходной функции: \n" , np.array(torch_conv))
print("Результат работы написанной функции: \n", my_conv)
print(np.allclose(my_conv, np.array(torch_conv)))

Результат работы исходной функции: 
 [[[[14. 18. 22.]
   [30. 34. 38.]
   [46. 50. 54.]]]]
Результат работы написанной функции: 
 [[[[14. 18. 22.]
   [30. 34. 38.]
   [46. 50. 54.]]]]
True
